import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { v4 as uuidv4 } from 'uuid';

export type EnrollmentTokenDocument = EnrollmentTokenEntity & Document;

/**
 * Enrollment token entity.
 * Generated by admin, consumed during SetupApp onboarding.
 * Single-use and time-limited.
 */
@Schema({
  collection: 'enrollment_tokens',
  timestamps: true,
  versionKey: false,
})
export class EnrollmentTokenEntity {
  @Prop({ type: String, default: () => uuidv4(), unique: true, index: true })
  uuid: string;

  @Prop({ required: true, unique: true, index: true })
  token: string;

  @Prop({ type: Types.ObjectId, ref: 'UserEntity', required: true, index: true })
  userId: Types.ObjectId;

  @Prop({ required: true })
  employeeId: string;

  @Prop({ required: true, type: Date })
  expiresAt: Date;

  @Prop({ default: false })
  isUsed: boolean;

  @Prop({ type: Date, default: null })
  usedAt: Date | null;

  @Prop({ type: String, default: null })
  usedByDeviceFingerprint: string | null;

  @Prop({ type: String, default: null })
  usedFromIp: string | null;

  @Prop({ required: true })
  createdBy: string;

  @Prop({ type: Number, default: 1 })
  maxDevices: number; // Max devices this token can enroll

  @Prop({ type: Number, default: 0 })
  usedCount: number;

  @Prop({ type: Object, default: {} })
  metadata: Record<string, any>;
}

export const EnrollmentTokenSchema = SchemaFactory.createForClass(EnrollmentTokenEntity);

// TTL index — auto-cleanup after expiry + 30 days grace
EnrollmentTokenSchema.index({ expiresAt: 1 }, { expireAfterSeconds: 2592000 });
EnrollmentTokenSchema.index({ token: 1, isUsed: 1 });
EnrollmentTokenSchema.index({ userId: 1 });
EnrollmentTokenSchema.index({ employeeId: 1 });
