import {
  IsString, IsNotEmpty, IsOptional, MaxLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * DTO for verifying enrollment token validity.
 */
export class VerifyTokenDto {
  @ApiProperty({
    example: 'enr_a1b2c3d4e5f6...',
    description: 'Enrollment token received from administrator',
  })
  @IsString()
  @IsNotEmpty()
  token: string;

  @ApiProperty({
    example: 'EMP-001',
    description: 'Employee ID assigned by the organization',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  employeeId: string;
}

/**
 * DTO for device enrollment via SetupApp.
 * Contains CSR, device fingerprint, and enrollment credentials.
 */
export class EnrollDeviceDto {
  @ApiProperty({
    example: 'enr_a1b2c3d4e5f6...',
    description: 'Enrollment token for device registration',
  })
  @IsString()
  @IsNotEmpty()
  enrollmentToken: string;

  @ApiProperty({
    example: 'EMP-001',
    description: 'Employee ID',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  employeeId: string;

  @ApiProperty({
    example: '-----BEGIN CERTIFICATE REQUEST-----\nMIIC...\n-----END CERTIFICATE REQUEST-----',
    description: 'PEM-encoded Certificate Signing Request generated by SetupApp',
  })
  @IsString()
  @IsNotEmpty()
  csr: string;

  @ApiProperty({
    example: 'abc123def456hash...',
    description: 'SHA-256 device fingerprint computed from hardware identifiers',
  })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;

  @ApiPropertyOptional({
    example: 'WORKSTATION-001',
    description: 'Hostname of the device',
  })
  @IsOptional()
  @IsString()
  @MaxLength(255)
  hostname?: string;

  @ApiPropertyOptional({
    example: 'win32',
    description: 'Operating system platform',
  })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  platform?: string;

  @ApiPropertyOptional({
    example: 'x64',
    description: 'CPU architecture',
  })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  arch?: string;

  @ApiPropertyOptional({
    example: 'Windows 11 Pro 23H2',
    description: 'OS version string',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  osVersion?: string;

  @ApiPropertyOptional({
    example: '00:1A:2B:3C:4D:5E',
    description: 'Primary MAC address',
  })
  @IsOptional()
  @IsString()
  @MaxLength(50)
  macAddress?: string;

  @ApiPropertyOptional({
    example: 'SN-1234567890',
    description: 'Device hardware serial number',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100)
  serialNumber?: string;
}

/**
 * DTO for generating certificate from validated enrollment.
 */
export class GenerateCertificateDto {
  @ApiProperty({
    example: '-----BEGIN CERTIFICATE REQUEST-----\nMIIC...\n-----END CERTIFICATE REQUEST-----',
    description: 'PEM-encoded Certificate Signing Request',
  })
  @IsString()
  @IsNotEmpty()
  csr: string;

  @ApiProperty({
    example: 'EMP-001',
    description: 'Employee ID to embed in the certificate',
  })
  @IsString()
  @IsNotEmpty()
  employeeId: string;

  @ApiProperty({
    example: 'dev_abc123...',
    description: 'Device ID to embed in the certificate',
  })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({
    example: 'abc123def456hash...',
    description: 'Device fingerprint to embed in the certificate',
  })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;

  @ApiPropertyOptional({
    example: '365d',
    description: 'Certificate validity period (e.g., 365d, 8760h)',
  })
  @IsOptional()
  @IsString()
  ttl?: string;
}

/**
 * DTO for certificate renewal.
 */
export class RenewCertificateDto {
  @ApiProperty({
    example: '-----BEGIN CERTIFICATE-----\nMIIC...\n-----END CERTIFICATE-----',
    description: 'Current valid certificate PEM for renewal',
  })
  @IsString()
  @IsNotEmpty()
  currentCertificate: string;

  @ApiProperty({
    example: '-----BEGIN CERTIFICATE REQUEST-----\nMIIC...\n-----END CERTIFICATE REQUEST-----',
    description: 'New CSR for the renewed certificate',
  })
  @IsString()
  @IsNotEmpty()
  newCsr: string;

  @ApiProperty({
    example: 'abc123def456hash...',
    description: 'Device fingerprint (must match the current certificate)',
  })
  @IsString()
  @IsNotEmpty()
  deviceFingerprint: string;
}
